version: '3'
services:
  bot:
    image: python:3.8
    command: python bot.py
    environment:
      - TELEGRAM_TOKEN=5837266855:AAGIuaQqoLuNJh4f-H01mi9Pu4_MkmlqbLk
      - CHAT_ID=SukamajuPetarunk
    volumes:
      - .:/app
    depends_on:
      - redis
